import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { VStack, Box } from "@chakra-ui/react"
import Header from '../components/header'
import Body from '../components/body'
import Questions from '../components/question'
import PageTwo from '../components/containerSecond'
export default function Home() {
  return (
    <div className={styles.app}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className={styles.container} bg="#F3C6BD" >
        <VStack className={styles.homePage} w="90%" m="0 auto">
          <Header />
          <Body />
        </VStack>
      </Box>
      <Questions />
      <PageTwo />
    </div>
  )
}
